# Generated by Django 4.1.5 on 2023-09-13 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('desc', models.CharField(help_text='简介', max_length=300, verbose_name='简介')),
                ('ip', models.CharField(help_text='IP地址', max_length=50, verbose_name='IP地址')),
                ('title', models.CharField(help_text='歌名', max_length=50, verbose_name='歌名')),
                ('singer', models.CharField(help_text='歌手', max_length=30, verbose_name='歌手')),
                ('avatar', models.URLField(help_text='图片', verbose_name='图片')),
                ('url', models.FileField(help_text='地址', upload_to='', verbose_name='地址')),
            ],
            options={
                'verbose_name': '背景音乐',
                'verbose_name_plural': '背景音乐',
                'db_table': '背景音乐',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('desc', models.CharField(help_text='简介', max_length=300, verbose_name='简介')),
                ('ip', models.CharField(help_text='IP地址', max_length=50, verbose_name='IP地址')),
                ('title', models.CharField(help_text='网站名', max_length=100, verbose_name='网站名')),
                ('avatar', models.URLField(help_text='avatar', verbose_name='avatar')),
                ('url', models.URLField(help_text='地址', verbose_name='地址')),
                ('weight', models.PositiveIntegerField(default=1, help_text='权重越高越靠前', verbose_name='权重')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
                'db_table': '友链',
                'ordering': ['-weight'],
            },
        ),
    ]
