# Generated by Django 4.1.5 on 2023-09-13 19:18

import datetime
from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('desc', models.CharField(help_text='简介', max_length=300, verbose_name='简介')),
                ('ip', models.CharField(help_text='IP地址', max_length=50, verbose_name='IP地址')),
                ('type', models.PositiveIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'audio'), (3, 'text'), (4, 'other')], default=0, help_text='类型', verbose_name='类型')),
                ('path', models.FileField(help_text='路径', upload_to=file.models.upload_to, verbose_name='路径')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': '文件',
            },
        ),
    ]
