# Generated by Django 4.1.5 on 2023-03-24 10:55

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.TextField(
                        db_column="请求路径",
                        default="/",
                        help_text="请求路径",
                        max_length=1000,
                        verbose_name="请求路径",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        db_column="请求方式",
                        default="GET",
                        help_text="请求方式",
                        max_length=100,
                        verbose_name="请求方式",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        db_column="IP地址",
                        help_text="IP地址",
                        max_length=50,
                        verbose_name="IP地址",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        db_column="请求头",
                        help_text="请求头",
                        max_length=500,
                        verbose_name="请求头",
                    ),
                ),
                (
                    "http_refer",
                    models.URLField(
                        db_column="跳转的网页", help_text="跳转的网页", verbose_name="跳转的网页"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        db_column="操作系统",
                        default="",
                        help_text="操作系统",
                        max_length=100,
                        verbose_name="操作系统",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_column="国家",
                        default="",
                        help_text="国家",
                        max_length=50,
                        verbose_name="国家",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        db_column="省份",
                        default="",
                        help_text="省份",
                        max_length=50,
                        verbose_name="省份",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_column="城市",
                        default="",
                        help_text="城市",
                        max_length=50,
                        verbose_name="城市",
                    ),
                ),
                (
                    "computer_name",
                    models.CharField(
                        db_column="计算机名",
                        default="",
                        help_text="计算机名",
                        max_length=50,
                        verbose_name="计算机名",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="用户名",
                        default="",
                        help_text="用户名",
                        max_length=50,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True, db_column="时间", help_text="时间", verbose_name="时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "请求记录",
                "verbose_name_plural": "请求记录",
                "db_table": "请求记录",
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        db_column="错误原因",
                        help_text="错误原因",
                        max_length=500,
                        verbose_name="错误原因",
                    ),
                ),
                (
                    "request_log",
                    models.ForeignKey(
                        db_column="IP地址",
                        help_text="IP地址",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log.requestrecord",
                        verbose_name="IP地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "错误日志",
                "verbose_name_plural": "错误日志",
                "db_table": "错误日志",
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "点赞"),
                            (1, "取消点赞"),
                            (2, "收藏"),
                            (3, "取消收藏"),
                            (4, "评论"),
                            (5, "删除评论"),
                            (6, "点击"),
                            (7, "阅读"),
                        ],
                        db_column="行为",
                        help_text="行为",
                        verbose_name="行为",
                    ),
                ),
                (
                    "cost_time",
                    models.PositiveIntegerField(
                        db_column="耗时", default=0, help_text="耗时", verbose_name="耗时"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        db_column="分值", default=0, help_text="分值", verbose_name="分值"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True, db_column="时间", help_text="时间", verbose_name="时间"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        db_column="博客",
                        help_text="博客",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blog",
                        verbose_name="博客",
                    ),
                ),
            ],
            bases=(models.Model, common.models.BaseModel),
        ),
    ]
