# Generated by Django 4.1.5 on 2023-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                blank=True,
                db_column="标题",
                help_text="标题",
                max_length=8,
                verbose_name="标题",
            ),
        ),
    ]
