# Generated by Django 4.1.5 on 2023-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_tag_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="avatar",
            field=models.CharField(
                blank=True,
                db_column="封面",
                default="image/default_blog_avatar.jpg",
                help_text="封面",
                max_length=500,
                verbose_name="封面",
            ),
        ),
    ]
