# Generated by Django 4.1.5 on 2023-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_alter_blog_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="recommendation_score",
            field=models.PositiveIntegerField(
                db_column="推荐分数", default=0, help_text="推荐分数", verbose_name="推荐分数"
            ),
        ),
    ]
