# Generated by Django 4.1.5 on 2023-04-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0010_alter_category_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog_Tag_Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        db_column="博客",
                        help_text="博客",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.blog",
                        verbose_name="博客",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="标签",
                        help_text="标签",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
        ),
    ]
