# Generated by Django 4.1.5 on 2023-03-24 10:55

import ckeditor_uploader.fields
import common.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_column="标题",
                        help_text="标题",
                        max_length=30,
                        verbose_name="标题",
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True,
                        db_column="封面",
                        default="image/a.jpg",
                        help_text="封面",
                        max_length=500,
                        verbose_name="封面",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        db_column="摘要",
                        help_text="摘要",
                        max_length=150,
                        verbose_name="摘要",
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        db_column="文章内容", help_text="文章内容", verbose_name="文章内容"
                    ),
                ),
                (
                    "dpv",
                    models.PositiveIntegerField(
                        db_column="dpv", default=0, help_text="dpv", verbose_name="dpv"
                    ),
                ),
                (
                    "duv",
                    models.PositiveIntegerField(
                        db_column="duv", default=0, help_text="duv", verbose_name="duv"
                    ),
                ),
                (
                    "pv",
                    models.PositiveIntegerField(
                        db_column="pv", default=0, help_text="pv", verbose_name="pv"
                    ),
                ),
                (
                    "uv",
                    models.PositiveIntegerField(
                        db_column="uv", default=0, help_text="uv", verbose_name="uv"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        db_column="创建时间",
                        default=datetime.datetime.now,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        db_column="最后修改时间",
                        default=datetime.datetime.now,
                        help_text="最后修改时间",
                        verbose_name="最后修改时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_column="文章是否已删除",
                        default=False,
                        help_text="文章是否已删除",
                        verbose_name="文章是否已删除",
                    ),
                ),
                (
                    "is_top",
                    models.BooleanField(
                        db_column="是否置顶",
                        default=False,
                        help_text="是否置顶",
                        verbose_name="是否置顶",
                    ),
                ),
                (
                    "read_time",
                    models.PositiveIntegerField(
                        db_column="预计阅读时长",
                        default=0,
                        help_text="预计阅读时长",
                        verbose_name="预计阅读时长",
                    ),
                ),
                (
                    "quality_score",
                    models.PositiveIntegerField(
                        db_column="质量分数",
                        default=10,
                        help_text="质量分数",
                        verbose_name="质量分数",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客",
                "verbose_name_plural": "博客",
                "db_table": "博客",
                "ordering": ["-is_top", "-create_time"],
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_column="分类",
                        help_text="分类",
                        max_length=8,
                        verbose_name="分类",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="创建时间",
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "分类",
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_canceled",
                    models.BooleanField(
                        db_column="收藏是否已取消",
                        default=False,
                        help_text="收藏是否已取消",
                        verbose_name="收藏是否已取消",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="收藏日期",
                        help_text="收藏日期",
                        verbose_name="收藏日期",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "db_table": "收藏",
                "ordering": ["-time"],
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        db_column="评论内容",
                        help_text="评论内容",
                        max_length=500,
                        verbose_name="评论内容",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="评论时间",
                        help_text="评论时间",
                        verbose_name="评论时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_column="是否已删除",
                        default=False,
                        help_text="是否已删除",
                        verbose_name="是否已删除",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "评论",
                "ordering": ["-time"],
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_canceled",
                    models.BooleanField(
                        db_column="点赞是否已取消",
                        default=False,
                        help_text="点赞是否已取消",
                        verbose_name="点赞是否已取消",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="点赞时间",
                        help_text="点赞时间",
                        verbose_name="点赞时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "点赞",
                "verbose_name_plural": "点赞",
                "db_table": "点赞",
                "ordering": ["-time"],
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "相关推荐",
                "verbose_name_plural": "相关推荐",
                "db_table": "相关推荐",
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        db_column="关键字",
                        help_text="关键字",
                        max_length=100,
                        verbose_name="关键字",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True, db_column="时间", help_text="时间", verbose_name="时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "搜索记录",
                "verbose_name_plural": "搜索记录",
                "db_table": "搜索记录",
                "ordering": ["-time"],
            },
            bases=(models.Model, common.models.BaseModel),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_column="标签",
                        help_text="标签",
                        max_length=5,
                        verbose_name="标签",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="创建时间",
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "db_table": "标签",
            },
            bases=(models.Model, common.models.BaseModel),
        ),
    ]
