# Generated by Django 4.1.5 on 2023-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                blank=True,
                db_column="标题",
                help_text="标题",
                max_length=5,
                verbose_name="标题",
            ),
        ),
    ]
