# Generated by Django 4.1.5 on 2023-03-24 10:55

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackgroundMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_column="歌名", help_text="歌名", max_length=50, verbose_name="歌名"
                    ),
                ),
                (
                    "singer",
                    models.CharField(
                        db_column="歌手", help_text="歌手", max_length=30, verbose_name="歌手"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        db_column="图片",
                        help_text="图片",
                        upload_to="image/%Y/%m/%d",
                        verbose_name="图片",
                    ),
                ),
                (
                    "path",
                    models.FileField(
                        db_column="地址",
                        help_text="地址",
                        upload_to="audio/%Y/%m/%d",
                        verbose_name="地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "背景音乐",
                "verbose_name_plural": "背景音乐",
                "db_table": "背景音乐",
            },
            bases=(models.Model, common.models.BaseModel),
        ),
    ]
